### ISSUE TITLE
Serial monitor max baudrate limited to 115200 (legacy IDE has 250000, 1000000, ...)

### ISSUE THREAD

**Issue by njz3** [arduino/serial-monitor#20]
### Describe the request

Compared to legacy IDE's serial monitor, it would be nice to get the "extra" baudrate like 230400, 250000, 500000, 1000000, and 2000000.

### Describe the current behavior

**serial-monitor** does not offer the option of some useful baudrates.

### Additional context

Additional requests:

- https://github.com/arduino/Arduino/issues/4439
- https://github.com/arduino/Arduino/issues/3879
- https://github.com/arduino/Arduino/issues/356
- https://github.com/arduino/Arduino/issues/142

**Comment by 877dev** [comment]
74880 is still missing? Why on earth..
